version: "3"
services:

  # Redis
  redis:
    build: docker/redis
    ports:
      - "6379:6379"

  # App
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - /var/log/access.log:/var/log/access.log
    links:
      - "redis"
